name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t container101.azurecr.io/insight-agent:latest .

      - name: Push Docker image to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login container101.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push container101.azurecr.io/insight-agent:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          app-name: insight-agent
          resource-group: container
          image: container101.azurecr.io/insight-agent:latest



